title: 코파일럿놀이터 시즌2
description: M365 코파일럿의 에이전트 핸즈온 컨텐츠를 제공합니다.
theme: just-the-docs

url: https://lanslote.github.io/copilot

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Color scheme supports "light" (default) and "dark"
color_scheme: light

collections:
  agent-HOL:
    permalink: "/:collection/:path/"
    output: true
  plugin-MES-HOL:
    permalink: "/:collection/:path/"
    output: true
  plugin-ME-HOL:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    agent-HOL:
      name: "M365 코파일럿 에이전트 핸즈온"
      nav_fold: false
    plugin-MES-HOL:
      name: "[Expired] VS Code 플러그인(ME-심플) 핸즈온"
      nav_fold: true
    plugin-ME-HOL:
      name: "[Expired] VS Code 플러그인(ME-Full) 핸즈온"
      nav_fold: true

#The colors grey-lt, grey-dk, purple, blue, green, yellow, and red are predefined
#callouts:
#  warning:
#    title: Warning
#    color: red
#  highlight:
#    title: Highlight
#    color: grey-lt
#  note:
#    title: Note
#    color: green  
#  important:
#    title: Important
#    color: blue

#You can change the default opacity (0.2) for all callouts
callouts_opacity: 0.2
#The value of callouts_level is either quiet or loud;
callouts_level: loud 

compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true    

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-LWCGP80DW7
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

