title: 코파일럿놀이터
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://lanslote.github.io/copilot

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

collections:
  plugin-ME-HOL:
    permalink: "/:collection/:path/"
    output: true
  plugin-API-HOL:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    plugin-ME-HOL:
      name: 코파일럿 플러그인 (ME) 핸즈온
      nav_fold: false
    plugin-API-HOL:
      name: 코파일럿 플러그인 (API) 핸즈온
      nav_fold: false

#The colors grey-lt, grey-dk, purple, blue, green, yellow, and red are predefined
callouts:
  warning:
    title: Warning
    color: red
  highlight:
    title: Highlight
    color: yellow
  note:
    title: Note
    color: green  
  important:
    title: Important
    color: blue

#You can change the default opacity (0.2) for all callouts
callouts_opacity: 0.2
#The value of callouts_level is either quiet or loud;
callouts_level: loud 

compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true    